"""
Finance Summary Cog
"""
import discord
from discord.ext import commands, tasks
from datetime import datetime, time, timezone, timedelta
from typing import Optional

from config import CHIP_CHANNEL_ID, FINANCE_CHANNEL_ID
from utils.logger import setup_logger
from services.youtube import get_youtube_service
from services.llm import get_llm_service

logger = setup_logger("cogs.finance")

# 定義台灣時區 (UTC+8)
TW_TZ = timezone(timedelta(hours=8))

SYSTEM_PROMPT = """你是一位專精於宏觀經濟分析的財經分析師，專長是將複雜的經濟資訊進行結構化整理，並用繁體中文清晰說明經濟現象的因果關係。

經濟分析框架：
1. 核心指標優先：以 GDP、CPI、失業率為主軸，結合貨幣政策、財政政策及資產價格變化
2. 深挖因果鏈條：連結二級指標（PMI、零售、貿易數據等），重點分析「因為...所以...」的邏輯關係
3. 比較分析：進行橫向比較（跨國/跨地區）和縱向比較（歷史趨勢），突顯經濟現象的意義

輸出原則：
- 使用繁體中文
- 重點突出結構化整理
- 優先呈現數據和因果關係"""

class Finance(commands.Cog):
    """金融資訊摘要功能"""
    
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        # Use FINANCE_CHANNEL_ID if set, otherwise fallback to CHIP_CHANNEL_ID
        self.channel_id = FINANCE_CHANNEL_ID or CHIP_CHANNEL_ID
        self.target_tag_name = "財經新聞"
        self.youtube = get_youtube_service()
        self.llm = get_llm_service()
        self.target_channel_id = "UC0lbAQVpenvfA2QqzsRtL_g" # @yutinghaofinance (游庭皓的財經皓角)
        
    async def cog_load(self):
        """Cog 載入時執行"""
        self.finance_daily_task.start()
        logger.info(f"Finance Cog 每日排程已啟動 (預定執行時間: {self.finance_daily_task.time})")
        
    async def cog_unload(self):
        """Cog 卸載時執行"""
        self.finance_daily_task.cancel()

    # 設定週一至週五 12:00 (UTC+8) 執行
    @tasks.loop(time=time(hour=12, minute=0, tzinfo=TW_TZ))
    async def finance_daily_task(self):
        """每日財經摘要任務"""
        today = datetime.now(TW_TZ)
        if today.weekday() >= 5:  # 週末跳過
            return

        logger.info("開始執行每日財經摘要任務")
        await self.run_finance_summary()

    async def run_finance_summary(self, ctx: commands.Context = None):
        """執行財經摘要邏輯 (可重複使用)"""
        try:
            # 1. Get latest video
            video = await self.youtube.get_latest_video(self.target_channel_id)
            if not video:
                msg = "找不到最新的影片資料"
                logger.warning(msg)
                if ctx: await ctx.send(f"❌ {msg}")
                return

            video_id = video.get("video_id")
            title = video.get("title")
            publish_date = video.get("publish_date") # ISO format
            
            # Check if video is from today (optional, but good practice to ensure freshness)
            # The requirement says "get latest video", so strictly speaking we take the latest.
            # But usually we want today's video. Let's just log the date.
            logger.info(f"Processing video: {title} ({video_id}), published at {publish_date}")

            # 2. Get transcript
            transcript = await self.youtube.get_video_transcript(video_id)
            if not transcript:
                msg = f"無法取得影片字幕: {title}"
                logger.warning(msg)
                if ctx: await ctx.send(f"❌ {msg}")
                return

            if ctx: await ctx.send(f"正在生成摘要: {title}...")

            # 3. Generate summary
            summary = await self.llm.generate_summary(transcript, SYSTEM_PROMPT)
            if not summary:
                msg = "摘要生成失敗"
                logger.error(msg)
                if ctx: await ctx.send(f"❌ {msg}")
                return

            # 4. Post to Discord (use regular message for proper markdown rendering)
            video_url = f"https://www.youtube.com/watch?v={video_id}"
            header = f"**📺 [{title}]({video_url})**\n\n"
            footer = "\n\n---\n*游庭皓的財經皓角 | Generated by AI*"
            
            # Discord message limit is 2000 characters
            max_content_length = 2000 - len(header) - len(footer)
            content = summary[:max_content_length] if len(summary) > max_content_length else summary
            full_message = header + content + footer
            
            # Decide where to send
            if ctx:
                await ctx.send(full_message)
            else:
                channel = self.bot.get_channel(self.channel_id)
                if not channel:
                    logger.error(f"找不到頻道 ID: {self.channel_id}")
                    return
                
                if isinstance(channel, discord.ForumChannel):
                    target_tag = None
                    for tag in channel.available_tags:
                        if tag.name == self.target_tag_name:
                            target_tag = tag
                            break
                    
                    tags = [target_tag] if target_tag else []
                    
                    await channel.create_thread(
                        name=f"📺 {title[:95]}",  # Discord thread name limit is 100 chars
                        content=full_message,
                        applied_tags=tags
                    )
                else:
                    await channel.send(full_message)
                    
            logger.info(f"已發送財經摘要: {title}")


        except Exception as e:
            logger.error(f"執行財經摘要任務失敗: {e}")
            if ctx: await ctx.send(f"❌ 發生錯誤: {e}")

    @finance_daily_task.before_loop
    async def before_daily_report(self):
        await self.bot.wait_until_ready()

    @commands.command(name="daily_finance")
    async def manual_finance(self, ctx: commands.Context):
        """手動觸發財經摘要"""
        await self.run_finance_summary(ctx)

async def setup(bot: commands.Bot):
    await bot.add_cog(Finance(bot))
